Revert "GH actions: try latest tags"
This reverts commit 791de9632feca653e9d989019c0f185efb3033f3.

Error: Unable to resolve action `actions/cache@latest`, unable to find version `latest`. Unable to resolve action `actions/checkout@latest`, unable to find version `latest`. Unable to resolve action `haskell/actions@latest`, unable to find version `latest`